export const DAYS = {
    SUNDAY: 0,
    MONDAY: 1,
    TUESDAY: 2,
    WEDNESDAY: 3,
    THURSDAY: 4,
    FRIDAY: 5,
    SATURDAY: 6
};

export const PEAK_TIME_START = 15;
export const PEAK_TIME_END = 19;

export const ITEM_COUNT_TRESHOLD = 5;

export const CART_VALUE_TRESHOLD = 200;

export const INITIAL_ORDER_SURCHARGE = 0;

export const CART_VALUE_CUTOFF = 10;

export const DELIVERY_DISTANCE_INITIAL_VALUE_CUTOFF = 1000;
export const DELIVERY_DISTANCE_VALUE_CUTOFF = 500;
export const DELIVERY_DISTANCE_INITIAL_VALUE_CUTOFF_SURCHARGE = 2;
export const DELIVERY_DISTANCE_EXTRA_SURCHARGE = 1;

export const MAXIMUM_DELIVERY_COST = 15;

export const PEAK_TIME_SURCHARGE_RATIO = 1.2;

export const ITEM_AMOUNT_CUTOFF = 12;

export const ORDER_SURCHARGE_RATIO = 0.5;

export const ITEM_AMOUNT_CUTOFF_SURCHARGE = 1.20;